---
- name: Ensure system locale in Apache envvars
  lineinfile: dest=/etc/apache2/envvars line=". /etc/default/locale" insertbefore="export LANG" backup=yes
  notify:
    - restart apache
- name: Apache uwsgi module deps
  apt: name=libapache2-mod-proxy-uwsgi
  notify:
    - restart apache
- name: Apache modules
  apache2_module: state=present name={{ item }}
  with_items:
    - proxy_uwsgi
    - proxy
    - ssl
  notify:
    - restart apache
- name: Apache site
  template: dest=/etc/apache2/sites-available/mailmanweb.conf src=apache.conf.j2
- name: Enable site
  command: a2ensite mailmanweb
  notify:
    - restart apache
