---
- name: Create database
  postgresql_db: name={{ mailman_db_web_name }}
  become_user: postgres
- name: Create user
  postgresql_user: db={{ mailman_db_web_name }} name={{ mailman_db_web_user }} password={{ mailman_db_web_password }} priv=ALL
  become_user: postgres
- name: Ensure user does not have unnecessary privilege
  postgresql_user: name={{ mailman_db_web_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become_user: postgres
