---
- name: stop sendmail
  service: name=sendmail state=stopped
  ignore_errors: yes
- name: restart postfix
  service: name=postfix state=restarted
- name: restart mailman
  service: name=mailman state=restarted
